// GENERATED by tools/update-protocol.py from protocol/codex/inventory.json. Do not edit.
// Source: codex-cli 0.157.1 (experimental API included: true).
package top.flysoftbeta.workflow.agent.codex

@Suppress("unused")
object CodexProtocol {
    const val VERSION = "codex-cli 0.157.1"

    /** 167 `clientRequests` methods, in schema order. */
    object ClientRequest {
        const val INITIALIZE = "initialize"
        const val SERVER_DIAGNOSTICS = "server/diagnostics"
        const val USER_VERIFICATION_STATUS = "userVerification/status"
        const val USER_VERIFICATION_ENROLL = "userVerification/enroll"
        const val USER_VERIFICATION_DELETE = "userVerification/delete"
        const val USER_VERIFICATION_VERIFY = "userVerification/verify"
        const val USER_VERIFICATION_CANCEL = "userVerification/cancel"
        const val THREAD_START = "thread/start"
        const val THREAD_RESUME = "thread/resume"
        const val THREAD_FORK = "thread/fork"
        const val THREAD_ARCHIVE = "thread/archive"
        const val THREAD_DELETE = "thread/delete"
        const val THREAD_UNSUBSCRIBE = "thread/unsubscribe"
        const val THREAD_INCREMENT_ELICITATION = "thread/increment_elicitation"
        const val THREAD_DECREMENT_ELICITATION = "thread/decrement_elicitation"
        const val THREAD_NAME_SET = "thread/name/set"
        const val THREAD_GOAL_SET = "thread/goal/set"
        const val THREAD_GOAL_GET = "thread/goal/get"
        const val THREAD_GOAL_CLEAR = "thread/goal/clear"
        const val THREAD_QUEUE_ADD = "thread/queue/add"
        const val THREAD_QUEUE_LIST = "thread/queue/list"
        const val THREAD_QUEUE_UPDATE = "thread/queue/update"
        const val THREAD_QUEUE_DELETE = "thread/queue/delete"
        const val THREAD_QUEUE_REORDER = "thread/queue/reorder"
        const val THREAD_QUEUE_START = "thread/queue/start"
        const val THREAD_METADATA_UPDATE = "thread/metadata/update"
        const val THREAD_ATTACHMENT_ADD = "thread/attachment/add"
        const val THREAD_ATTACHMENT_LIST = "thread/attachment/list"
        const val THREAD_ATTACHMENT_REMOVE = "thread/attachment/remove"
        const val THREAD_SECTION_MOVE = "thread/section/move"
        const val THREAD_SETTINGS_UPDATE = "thread/settings/update"
        const val THREAD_MEMORY_MODE_SET = "thread/memoryMode/set"
        const val MEMORY_STATUS = "memory/status"
        const val MEMORY_RESET = "memory/reset"
        const val ROLLOUT_COMPRESS = "rollout/compress"
        const val THREAD_UNARCHIVE = "thread/unarchive"
        const val THREAD_COMPACT_START = "thread/compact/start"
        const val THREAD_SHELL_COMMAND = "thread/shellCommand"
        const val THREAD_APPROVE_GUARDIAN_DENIED_ACTION = "thread/approveGuardianDeniedAction"
        const val THREAD_BACKGROUND_TERMINALS_CLEAN = "thread/backgroundTerminals/clean"
        const val THREAD_BACKGROUND_TERMINALS_LIST = "thread/backgroundTerminals/list"
        const val THREAD_BACKGROUND_TERMINALS_TERMINATE = "thread/backgroundTerminals/terminate"
        const val THREAD_REVERT = "thread/revert"
        const val THREAD_LIST = "thread/list"
        const val PROJECT_LIST = "project/list"
        const val PROJECT_READ = "project/read"
        const val PROJECT_CREATE = "project/create"
        const val PROJECT_IMPORT = "project/import"
        const val PROJECT_UPDATE = "project/update"
        const val PROJECT_MOVE = "project/move"
        const val PROJECT_DELETE = "project/delete"
        const val THREAD_SECTION_LIST = "threadSection/list"
        const val THREAD_SECTION_CREATE = "threadSection/create"
        const val THREAD_SECTION_UPDATE = "threadSection/update"
        const val THREAD_SECTION_DELETE = "threadSection/delete"
        const val THREAD_SEARCH = "thread/search"
        const val THREAD_SEARCH_OCCURRENCES = "thread/searchOccurrences"
        const val THREAD_LOADED_LIST = "thread/loaded/list"
        const val THREAD_READ = "thread/read"
        const val THREAD_TURNS_LIST = "thread/turns/list"
        const val THREAD_ITEMS_LIST = "thread/items/list"
        const val THREAD_INJECT_ITEMS = "thread/inject_items"
        const val SKILLS_LIST = "skills/list"
        const val SKILLS_EXTRA_ROOTS_SET = "skills/extraRoots/set"
        const val HOOKS_LIST = "hooks/list"
        const val MARKETPLACE_ADD = "marketplace/add"
        const val MARKETPLACE_REMOVE = "marketplace/remove"
        const val MARKETPLACE_UPGRADE = "marketplace/upgrade"
        const val PLUGIN_LIST = "plugin/list"
        const val PLUGIN_SEARCH = "plugin/search"
        const val PLUGIN_INSTALLED = "plugin/installed"
        const val PLUGIN_RECONCILE = "plugin/reconcile"
        const val PLUGIN_READ = "plugin/read"
        const val PLUGIN_SKILL_READ = "plugin/skill/read"
        const val PLUGIN_SHARE_SAVE = "plugin/share/save"
        const val PLUGIN_SHARE_UPDATE_TARGETS = "plugin/share/updateTargets"
        const val PLUGIN_SHARE_LIST = "plugin/share/list"
        const val PLUGIN_SHARE_CHECKOUT = "plugin/share/checkout"
        const val PLUGIN_SHARE_DELETE = "plugin/share/delete"
        const val APP_READ = "app/read"
        const val APP_LIST = "app/list"
        const val APP_INSTALLED = "app/installed"
        const val FS_READ_FILE = "fs/readFile"
        const val FS_WRITE_FILE = "fs/writeFile"
        const val FS_CREATE_DIRECTORY = "fs/createDirectory"
        const val FS_GET_METADATA = "fs/getMetadata"
        const val FS_READ_DIRECTORY = "fs/readDirectory"
        const val FS_REMOVE = "fs/remove"
        const val FS_COPY = "fs/copy"
        const val FS_WATCH = "fs/watch"
        const val FS_UNWATCH = "fs/unwatch"
        const val SKILLS_CONFIG_WRITE = "skills/config/write"
        const val PLUGIN_INSTALL = "plugin/install"
        const val PLUGIN_UNINSTALL = "plugin/uninstall"
        const val TURN_START = "turn/start"
        const val TURN_SETTINGS_UPDATE = "turn/settings/update"
        const val TURN_STEER = "turn/steer"
        const val TURN_INTERRUPT = "turn/interrupt"
        const val THREAD_REALTIME_START = "thread/realtime/start"
        const val THREAD_REALTIME_APPEND_AUDIO = "thread/realtime/appendAudio"
        const val THREAD_REALTIME_APPEND_TEXT = "thread/realtime/appendText"
        const val THREAD_REALTIME_APPEND_SPEECH = "thread/realtime/appendSpeech"
        const val THREAD_REALTIME_STOP = "thread/realtime/stop"
        const val THREAD_TIMELINE_LIST = "thread/timeline/list"
        const val THREAD_REALTIME_LIST_VOICES = "thread/realtime/listVoices"
        const val REVIEW_START = "review/start"
        const val MODEL_LIST = "model/list"
        const val ACCOUNT_GATEWAY_OAUTH_READ = "account/gatewayOAuth/read"
        const val ACCOUNT_GATEWAY_OAUTH_LOGIN = "account/gatewayOAuth/login"
        const val ACCOUNT_GATEWAY_OAUTH_CANCEL = "account/gatewayOAuth/cancel"
        const val MODEL_PROVIDER_CAPABILITIES_READ = "modelProvider/capabilities/read"
        const val EXPERIMENTAL_FEATURE_LIST = "experimentalFeature/list"
        const val PERMISSION_PROFILE_LIST = "permissionProfile/list"
        const val EXPERIMENTAL_FEATURE_ENABLEMENT_SET = "experimentalFeature/enablement/set"
        const val REMOTE_CONTROL_ENABLE = "remoteControl/enable"
        const val REMOTE_CONTROL_DISABLE = "remoteControl/disable"
        const val REMOTE_CONTROL_STATUS_READ = "remoteControl/status/read"
        const val REMOTE_CONTROL_PAIRING_START = "remoteControl/pairing/start"
        const val REMOTE_CONTROL_PAIRING_STATUS = "remoteControl/pairing/status"
        const val REMOTE_CONTROL_CLIENT_LIST = "remoteControl/client/list"
        const val REMOTE_CONTROL_CLIENT_REVOKE = "remoteControl/client/revoke"
        const val COLLABORATION_MODE_LIST = "collaborationMode/list"
        const val MOCK_EXPERIMENTAL_METHOD = "mock/experimentalMethod"
        const val ENVIRONMENT_ADD = "environment/add"
        const val ENVIRONMENT_INFO = "environment/info"
        const val ENVIRONMENT_STATUS = "environment/status"
        const val MCP_SERVER_OAUTH_LOGIN = "mcpServer/oauth/login"
        const val CONFIG_MCP_SERVER_RELOAD = "config/mcpServer/reload"
        const val MCP_SERVER_STATUS_LIST = "mcpServerStatus/list"
        const val MCP_SERVER_RESOURCE_READ = "mcpServer/resource/read"
        const val MCP_SERVER_EVENT_STREAM_START = "mcpServer/event/stream/start"
        const val MCP_SERVER_EVENT_STREAM_STOP = "mcpServer/event/stream/stop"
        const val MCP_SERVER_TOOL_CALL = "mcpServer/tool/call"
        const val WINDOWS_SANDBOX_SETUP_START = "windowsSandbox/setupStart"
        const val WINDOWS_SANDBOX_READINESS = "windowsSandbox/readiness"
        const val ACCOUNT_LOGIN_START = "account/login/start"
        const val ACCOUNT_BEDROCK_DISCOVER = "account/bedrock/discover"
        const val ACCOUNT_BEDROCK_SETUP = "account/bedrock/setup"
        const val ACCOUNT_LOGIN_CANCEL = "account/login/cancel"
        const val ACCOUNT_LOGOUT = "account/logout"
        const val ACCOUNT_RATE_LIMITS_READ = "account/rateLimits/read"
        const val ACCOUNT_RATE_LIMIT_RESET_CREDIT_CONSUME = "account/rateLimitResetCredit/consume"
        const val ACCOUNT_USAGE_READ = "account/usage/read"
        const val ACCOUNT_WORKSPACE_MESSAGES_READ = "account/workspaceMessages/read"
        const val ACCOUNT_SEND_ADD_CREDITS_NUDGE_EMAIL = "account/sendAddCreditsNudgeEmail"
        const val FEEDBACK_UPLOAD = "feedback/upload"
        const val COMMAND_EXEC = "command/exec"
        const val COMMAND_EXEC_WRITE = "command/exec/write"
        const val COMMAND_EXEC_TERMINATE = "command/exec/terminate"
        const val COMMAND_EXEC_RESIZE = "command/exec/resize"
        const val PROCESS_SPAWN = "process/spawn"
        const val PROCESS_WRITE_STDIN = "process/writeStdin"
        const val PROCESS_KILL = "process/kill"
        const val PROCESS_RESIZE_PTY = "process/resizePty"
        const val CONFIG_READ = "config/read"
        const val EXTERNAL_AGENT_CONFIG_DETECT = "externalAgentConfig/detect"
        const val EXTERNAL_AGENT_CONFIG_IMPORT = "externalAgentConfig/import"
        const val EXTERNAL_AGENT_CONFIG_IMPORT_RECORD_HISTORY = "externalAgentConfig/import/recordHistory"
        const val EXTERNAL_AGENT_CONFIG_IMPORT_READ_HISTORIES = "externalAgentConfig/import/readHistories"
        const val CONFIG_VALUE_WRITE = "config/value/write"
        const val CONFIG_BATCH_WRITE = "config/batchWrite"
        const val CONFIG_REQUIREMENTS_READ = "configRequirements/read"
        const val ACCOUNT_READ = "account/read"
        const val FUZZY_FILE_SEARCH = "fuzzyFileSearch"
        const val FUZZY_FILE_SEARCH_SESSION_START = "fuzzyFileSearch/sessionStart"
        const val FUZZY_FILE_SEARCH_SESSION_UPDATE = "fuzzyFileSearch/sessionUpdate"
        const val FUZZY_FILE_SEARCH_SESSION_STOP = "fuzzyFileSearch/sessionStop"

        val ALL: List<String> = listOf(
            INITIALIZE,
            SERVER_DIAGNOSTICS,
            USER_VERIFICATION_STATUS,
            USER_VERIFICATION_ENROLL,
            USER_VERIFICATION_DELETE,
            USER_VERIFICATION_VERIFY,
            USER_VERIFICATION_CANCEL,
            THREAD_START,
            THREAD_RESUME,
            THREAD_FORK,
            THREAD_ARCHIVE,
            THREAD_DELETE,
            THREAD_UNSUBSCRIBE,
            THREAD_INCREMENT_ELICITATION,
            THREAD_DECREMENT_ELICITATION,
            THREAD_NAME_SET,
            THREAD_GOAL_SET,
            THREAD_GOAL_GET,
            THREAD_GOAL_CLEAR,
            THREAD_QUEUE_ADD,
            THREAD_QUEUE_LIST,
            THREAD_QUEUE_UPDATE,
            THREAD_QUEUE_DELETE,
            THREAD_QUEUE_REORDER,
            THREAD_QUEUE_START,
            THREAD_METADATA_UPDATE,
            THREAD_ATTACHMENT_ADD,
            THREAD_ATTACHMENT_LIST,
            THREAD_ATTACHMENT_REMOVE,
            THREAD_SECTION_MOVE,
            THREAD_SETTINGS_UPDATE,
            THREAD_MEMORY_MODE_SET,
            MEMORY_STATUS,
            MEMORY_RESET,
            ROLLOUT_COMPRESS,
            THREAD_UNARCHIVE,
            THREAD_COMPACT_START,
            THREAD_SHELL_COMMAND,
            THREAD_APPROVE_GUARDIAN_DENIED_ACTION,
            THREAD_BACKGROUND_TERMINALS_CLEAN,
            THREAD_BACKGROUND_TERMINALS_LIST,
            THREAD_BACKGROUND_TERMINALS_TERMINATE,
            THREAD_REVERT,
            THREAD_LIST,
            PROJECT_LIST,
            PROJECT_READ,
            PROJECT_CREATE,
            PROJECT_IMPORT,
            PROJECT_UPDATE,
            PROJECT_MOVE,
            PROJECT_DELETE,
            THREAD_SECTION_LIST,
            THREAD_SECTION_CREATE,
            THREAD_SECTION_UPDATE,
            THREAD_SECTION_DELETE,
            THREAD_SEARCH,
            THREAD_SEARCH_OCCURRENCES,
            THREAD_LOADED_LIST,
            THREAD_READ,
            THREAD_TURNS_LIST,
            THREAD_ITEMS_LIST,
            THREAD_INJECT_ITEMS,
            SKILLS_LIST,
            SKILLS_EXTRA_ROOTS_SET,
            HOOKS_LIST,
            MARKETPLACE_ADD,
            MARKETPLACE_REMOVE,
            MARKETPLACE_UPGRADE,
            PLUGIN_LIST,
            PLUGIN_SEARCH,
            PLUGIN_INSTALLED,
            PLUGIN_RECONCILE,
            PLUGIN_READ,
            PLUGIN_SKILL_READ,
            PLUGIN_SHARE_SAVE,
            PLUGIN_SHARE_UPDATE_TARGETS,
            PLUGIN_SHARE_LIST,
            PLUGIN_SHARE_CHECKOUT,
            PLUGIN_SHARE_DELETE,
            APP_READ,
            APP_LIST,
            APP_INSTALLED,
            FS_READ_FILE,
            FS_WRITE_FILE,
            FS_CREATE_DIRECTORY,
            FS_GET_METADATA,
            FS_READ_DIRECTORY,
            FS_REMOVE,
            FS_COPY,
            FS_WATCH,
            FS_UNWATCH,
            SKILLS_CONFIG_WRITE,
            PLUGIN_INSTALL,
            PLUGIN_UNINSTALL,
            TURN_START,
            TURN_SETTINGS_UPDATE,
            TURN_STEER,
            TURN_INTERRUPT,
            THREAD_REALTIME_START,
            THREAD_REALTIME_APPEND_AUDIO,
            THREAD_REALTIME_APPEND_TEXT,
            THREAD_REALTIME_APPEND_SPEECH,
            THREAD_REALTIME_STOP,
            THREAD_TIMELINE_LIST,
            THREAD_REALTIME_LIST_VOICES,
            REVIEW_START,
            MODEL_LIST,
            ACCOUNT_GATEWAY_OAUTH_READ,
            ACCOUNT_GATEWAY_OAUTH_LOGIN,
            ACCOUNT_GATEWAY_OAUTH_CANCEL,
            MODEL_PROVIDER_CAPABILITIES_READ,
            EXPERIMENTAL_FEATURE_LIST,
            PERMISSION_PROFILE_LIST,
            EXPERIMENTAL_FEATURE_ENABLEMENT_SET,
            REMOTE_CONTROL_ENABLE,
            REMOTE_CONTROL_DISABLE,
            REMOTE_CONTROL_STATUS_READ,
            REMOTE_CONTROL_PAIRING_START,
            REMOTE_CONTROL_PAIRING_STATUS,
            REMOTE_CONTROL_CLIENT_LIST,
            REMOTE_CONTROL_CLIENT_REVOKE,
            COLLABORATION_MODE_LIST,
            MOCK_EXPERIMENTAL_METHOD,
            ENVIRONMENT_ADD,
            ENVIRONMENT_INFO,
            ENVIRONMENT_STATUS,
            MCP_SERVER_OAUTH_LOGIN,
            CONFIG_MCP_SERVER_RELOAD,
            MCP_SERVER_STATUS_LIST,
            MCP_SERVER_RESOURCE_READ,
            MCP_SERVER_EVENT_STREAM_START,
            MCP_SERVER_EVENT_STREAM_STOP,
            MCP_SERVER_TOOL_CALL,
            WINDOWS_SANDBOX_SETUP_START,
            WINDOWS_SANDBOX_READINESS,
            ACCOUNT_LOGIN_START,
            ACCOUNT_BEDROCK_DISCOVER,
            ACCOUNT_BEDROCK_SETUP,
            ACCOUNT_LOGIN_CANCEL,
            ACCOUNT_LOGOUT,
            ACCOUNT_RATE_LIMITS_READ,
            ACCOUNT_RATE_LIMIT_RESET_CREDIT_CONSUME,
            ACCOUNT_USAGE_READ,
            ACCOUNT_WORKSPACE_MESSAGES_READ,
            ACCOUNT_SEND_ADD_CREDITS_NUDGE_EMAIL,
            FEEDBACK_UPLOAD,
            COMMAND_EXEC,
            COMMAND_EXEC_WRITE,
            COMMAND_EXEC_TERMINATE,
            COMMAND_EXEC_RESIZE,
            PROCESS_SPAWN,
            PROCESS_WRITE_STDIN,
            PROCESS_KILL,
            PROCESS_RESIZE_PTY,
            CONFIG_READ,
            EXTERNAL_AGENT_CONFIG_DETECT,
            EXTERNAL_AGENT_CONFIG_IMPORT,
            EXTERNAL_AGENT_CONFIG_IMPORT_RECORD_HISTORY,
            EXTERNAL_AGENT_CONFIG_IMPORT_READ_HISTORIES,
            CONFIG_VALUE_WRITE,
            CONFIG_BATCH_WRITE,
            CONFIG_REQUIREMENTS_READ,
            ACCOUNT_READ,
            FUZZY_FILE_SEARCH,
            FUZZY_FILE_SEARCH_SESSION_START,
            FUZZY_FILE_SEARCH_SESSION_UPDATE,
            FUZZY_FILE_SEARCH_SESSION_STOP,
        )
    }

    /** 11 `serverRequests` methods, in schema order. */
    object ServerRequest {
        const val ITEM_COMMAND_EXECUTION_REQUEST_APPROVAL = "item/commandExecution/requestApproval"
        const val ITEM_FILE_CHANGE_REQUEST_APPROVAL = "item/fileChange/requestApproval"
        const val ITEM_TOOL_REQUEST_USER_INPUT = "item/tool/requestUserInput"
        const val MCP_SERVER_ELICITATION_REQUEST = "mcpServer/elicitation/request"
        const val ITEM_PERMISSIONS_REQUEST_APPROVAL = "item/permissions/requestApproval"
        const val ITEM_TOOL_CALL = "item/tool/call"
        const val ACCOUNT_CHATGPT_AUTH_TOKENS_REFRESH = "account/chatgptAuthTokens/refresh"
        const val ATTESTATION_GENERATE = "attestation/generate"
        const val CURRENT_TIME_READ = "currentTime/read"
        const val APPLY_PATCH_APPROVAL = "applyPatchApproval"
        const val EXEC_COMMAND_APPROVAL = "execCommandApproval"

        val ALL: List<String> = listOf(
            ITEM_COMMAND_EXECUTION_REQUEST_APPROVAL,
            ITEM_FILE_CHANGE_REQUEST_APPROVAL,
            ITEM_TOOL_REQUEST_USER_INPUT,
            MCP_SERVER_ELICITATION_REQUEST,
            ITEM_PERMISSIONS_REQUEST_APPROVAL,
            ITEM_TOOL_CALL,
            ACCOUNT_CHATGPT_AUTH_TOKENS_REFRESH,
            ATTESTATION_GENERATE,
            CURRENT_TIME_READ,
            APPLY_PATCH_APPROVAL,
            EXEC_COMMAND_APPROVAL,
        )
    }

    /** 83 `serverNotifications` methods, in schema order. */
    object ServerNotification {
        const val ERROR = "error"
        const val THREAD_STARTED = "thread/started"
        const val THREAD_STATUS_CHANGED = "thread/status/changed"
        const val THREAD_ARCHIVED = "thread/archived"
        const val THREAD_DELETED = "thread/deleted"
        const val THREAD_UNARCHIVED = "thread/unarchived"
        const val THREAD_CLOSED = "thread/closed"
        const val THREAD_REVERTED = "thread/reverted"
        const val SKILLS_CHANGED = "skills/changed"
        const val THREAD_NAME_UPDATED = "thread/name/updated"
        const val THREAD_ATTACHMENT_UPDATED = "thread/attachment/updated"
        const val THREAD_GOAL_UPDATED = "thread/goal/updated"
        const val THREAD_GOAL_CLEARED = "thread/goal/cleared"
        const val THREAD_QUEUE_CHANGED = "thread/queue/changed"
        const val PROJECT_CHANGED = "project/changed"
        const val THREAD_PROJECT_UPDATED = "thread/project/updated"
        const val THREAD_ENVIRONMENT_CONNECTED = "thread/environment/connected"
        const val THREAD_ENVIRONMENT_DISCONNECTED = "thread/environment/disconnected"
        const val THREAD_SETTINGS_UPDATED = "thread/settings/updated"
        const val THREAD_TOKEN_USAGE_UPDATED = "thread/tokenUsage/updated"
        const val TURN_STARTED = "turn/started"
        const val HOOK_STARTED = "hook/started"
        const val TURN_COMPLETED = "turn/completed"
        const val HOOK_COMPLETED = "hook/completed"
        const val TURN_DIFF_UPDATED = "turn/diff/updated"
        const val TURN_PLAN_UPDATED = "turn/plan/updated"
        const val ITEM_STARTED = "item/started"
        const val ITEM_AUTO_APPROVAL_REVIEW_STARTED = "item/autoApprovalReview/started"
        const val ITEM_AUTO_APPROVAL_REVIEW_COMPLETED = "item/autoApprovalReview/completed"
        const val AUTO_APPROVAL_REVIEW_STRICT_REVIEW_REQUIRED = "autoApprovalReview/strictReviewRequired"
        const val ITEM_COMPLETED = "item/completed"
        const val ITEM_AGENT_MESSAGE_DELTA = "item/agentMessage/delta"
        const val ITEM_PLAN_DELTA = "item/plan/delta"
        const val COMMAND_EXEC_OUTPUT_DELTA = "command/exec/outputDelta"
        const val PROCESS_OUTPUT_DELTA = "process/outputDelta"
        const val PROCESS_EXITED = "process/exited"
        const val ITEM_COMMAND_EXECUTION_OUTPUT_DELTA = "item/commandExecution/outputDelta"
        const val ITEM_COMMAND_EXECUTION_TERMINAL_INTERACTION = "item/commandExecution/terminalInteraction"
        const val ITEM_FILE_CHANGE_OUTPUT_DELTA = "item/fileChange/outputDelta"
        const val ITEM_FILE_CHANGE_PATCH_UPDATED = "item/fileChange/patchUpdated"
        const val SERVER_REQUEST_RESOLVED = "serverRequest/resolved"
        const val ITEM_MCP_TOOL_CALL_PROGRESS = "item/mcpToolCall/progress"
        const val MCP_SERVER_OAUTH_LOGIN_COMPLETED = "mcpServer/oauthLogin/completed"
        const val MCP_SERVER_STARTUP_STATUS_UPDATED = "mcpServer/startupStatus/updated"
        const val MCP_SERVER_EVENT_STREAM_NOTIFICATION = "mcpServer/event/stream/notification"
        const val ACCOUNT_UPDATED = "account/updated"
        const val ACCOUNT_GATEWAY_OAUTH_CHANGED = "account/gatewayOAuth/changed"
        const val ACCOUNT_RATE_LIMITS_UPDATED = "account/rateLimits/updated"
        const val APP_LIST_UPDATED = "app/list/updated"
        const val REMOTE_CONTROL_STATUS_CHANGED = "remoteControl/status/changed"
        const val EXTERNAL_AGENT_CONFIG_IMPORT_PROGRESS = "externalAgentConfig/import/progress"
        const val EXTERNAL_AGENT_CONFIG_IMPORT_COMPLETED = "externalAgentConfig/import/completed"
        const val FS_CHANGED = "fs/changed"
        const val ITEM_REASONING_SUMMARY_TEXT_DELTA = "item/reasoning/summaryTextDelta"
        const val ITEM_REASONING_SUMMARY_PART_ADDED = "item/reasoning/summaryPartAdded"
        const val ITEM_REASONING_TEXT_DELTA = "item/reasoning/textDelta"
        const val THREAD_COMPACTED = "thread/compacted"
        const val MODEL_REROUTED = "model/rerouted"
        const val MODEL_VERIFICATION = "model/verification"
        const val MODEL_PROVIDER_AUTH_RECOVERY_STARTED = "modelProvider/authRecoveryStarted"
        const val MODEL_PROVIDER_AUTH_RECOVERY_COMPLETED = "modelProvider/authRecoveryCompleted"
        const val TURN_MODERATION_METADATA = "turn/moderationMetadata"
        const val MODEL_SAFETY_BUFFERING_UPDATED = "model/safetyBuffering/updated"
        const val WARNING = "warning"
        const val GUARDIAN_WARNING = "guardianWarning"
        const val DEPRECATION_NOTICE = "deprecationNotice"
        const val CONFIG_WARNING = "configWarning"
        const val FUZZY_FILE_SEARCH_SESSION_UPDATED = "fuzzyFileSearch/sessionUpdated"
        const val FUZZY_FILE_SEARCH_SESSION_COMPLETED = "fuzzyFileSearch/sessionCompleted"
        const val THREAD_REALTIME_STARTED = "thread/realtime/started"
        const val THREAD_REALTIME_ITEM_ADDED = "thread/realtime/itemAdded"
        const val THREAD_REALTIME_ITEM_STARTED = "thread/realtime/item/started"
        const val THREAD_REALTIME_ITEM_TRANSCRIPT_DELTA = "thread/realtime/item/transcript/delta"
        const val THREAD_REALTIME_ITEM_COMPLETED = "thread/realtime/item/completed"
        const val THREAD_REALTIME_TRANSCRIPT_DELTA = "thread/realtime/transcript/delta"
        const val THREAD_REALTIME_TRANSCRIPT_DONE = "thread/realtime/transcript/done"
        const val THREAD_REALTIME_OUTPUT_AUDIO_DELTA = "thread/realtime/outputAudio/delta"
        const val THREAD_REALTIME_SDP = "thread/realtime/sdp"
        const val THREAD_REALTIME_ERROR = "thread/realtime/error"
        const val THREAD_REALTIME_CLOSED = "thread/realtime/closed"
        const val WINDOWS_WORLD_WRITABLE_WARNING = "windows/worldWritableWarning"
        const val WINDOWS_SANDBOX_SETUP_COMPLETED = "windowsSandbox/setupCompleted"
        const val ACCOUNT_LOGIN_COMPLETED = "account/login/completed"

        val ALL: List<String> = listOf(
            ERROR,
            THREAD_STARTED,
            THREAD_STATUS_CHANGED,
            THREAD_ARCHIVED,
            THREAD_DELETED,
            THREAD_UNARCHIVED,
            THREAD_CLOSED,
            THREAD_REVERTED,
            SKILLS_CHANGED,
            THREAD_NAME_UPDATED,
            THREAD_ATTACHMENT_UPDATED,
            THREAD_GOAL_UPDATED,
            THREAD_GOAL_CLEARED,
            THREAD_QUEUE_CHANGED,
            PROJECT_CHANGED,
            THREAD_PROJECT_UPDATED,
            THREAD_ENVIRONMENT_CONNECTED,
            THREAD_ENVIRONMENT_DISCONNECTED,
            THREAD_SETTINGS_UPDATED,
            THREAD_TOKEN_USAGE_UPDATED,
            TURN_STARTED,
            HOOK_STARTED,
            TURN_COMPLETED,
            HOOK_COMPLETED,
            TURN_DIFF_UPDATED,
            TURN_PLAN_UPDATED,
            ITEM_STARTED,
            ITEM_AUTO_APPROVAL_REVIEW_STARTED,
            ITEM_AUTO_APPROVAL_REVIEW_COMPLETED,
            AUTO_APPROVAL_REVIEW_STRICT_REVIEW_REQUIRED,
            ITEM_COMPLETED,
            ITEM_AGENT_MESSAGE_DELTA,
            ITEM_PLAN_DELTA,
            COMMAND_EXEC_OUTPUT_DELTA,
            PROCESS_OUTPUT_DELTA,
            PROCESS_EXITED,
            ITEM_COMMAND_EXECUTION_OUTPUT_DELTA,
            ITEM_COMMAND_EXECUTION_TERMINAL_INTERACTION,
            ITEM_FILE_CHANGE_OUTPUT_DELTA,
            ITEM_FILE_CHANGE_PATCH_UPDATED,
            SERVER_REQUEST_RESOLVED,
            ITEM_MCP_TOOL_CALL_PROGRESS,
            MCP_SERVER_OAUTH_LOGIN_COMPLETED,
            MCP_SERVER_STARTUP_STATUS_UPDATED,
            MCP_SERVER_EVENT_STREAM_NOTIFICATION,
            ACCOUNT_UPDATED,
            ACCOUNT_GATEWAY_OAUTH_CHANGED,
            ACCOUNT_RATE_LIMITS_UPDATED,
            APP_LIST_UPDATED,
            REMOTE_CONTROL_STATUS_CHANGED,
            EXTERNAL_AGENT_CONFIG_IMPORT_PROGRESS,
            EXTERNAL_AGENT_CONFIG_IMPORT_COMPLETED,
            FS_CHANGED,
            ITEM_REASONING_SUMMARY_TEXT_DELTA,
            ITEM_REASONING_SUMMARY_PART_ADDED,
            ITEM_REASONING_TEXT_DELTA,
            THREAD_COMPACTED,
            MODEL_REROUTED,
            MODEL_VERIFICATION,
            MODEL_PROVIDER_AUTH_RECOVERY_STARTED,
            MODEL_PROVIDER_AUTH_RECOVERY_COMPLETED,
            TURN_MODERATION_METADATA,
            MODEL_SAFETY_BUFFERING_UPDATED,
            WARNING,
            GUARDIAN_WARNING,
            DEPRECATION_NOTICE,
            CONFIG_WARNING,
            FUZZY_FILE_SEARCH_SESSION_UPDATED,
            FUZZY_FILE_SEARCH_SESSION_COMPLETED,
            THREAD_REALTIME_STARTED,
            THREAD_REALTIME_ITEM_ADDED,
            THREAD_REALTIME_ITEM_STARTED,
            THREAD_REALTIME_ITEM_TRANSCRIPT_DELTA,
            THREAD_REALTIME_ITEM_COMPLETED,
            THREAD_REALTIME_TRANSCRIPT_DELTA,
            THREAD_REALTIME_TRANSCRIPT_DONE,
            THREAD_REALTIME_OUTPUT_AUDIO_DELTA,
            THREAD_REALTIME_SDP,
            THREAD_REALTIME_ERROR,
            THREAD_REALTIME_CLOSED,
            WINDOWS_WORLD_WRITABLE_WARNING,
            WINDOWS_SANDBOX_SETUP_COMPLETED,
            ACCOUNT_LOGIN_COMPLETED,
        )
    }

    /** 1 `clientNotifications` methods, in schema order. */
    object ClientNotification {
        const val INITIALIZED = "initialized"

        val ALL: List<String> = listOf(
            INITIALIZED,
        )
    }
}
