[workspace]
members = ["environment", "environment/runtime", "environment/loader", "workspace", "filework", "terminal", "server"]
resolver = "3"

[workspace.package]
version = "1.0.0"
edition = "2024"
rust-version = "1.93"

[workspace.dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["raw_value", "arbitrary_precision"] }
schemars = "=1.2.2"
libc = "=0.2.189"
sha2 = "=0.11.0"
base64 = "=0.23.1"
uuid = { version = "=1.26.1", features = ["v4", "serde"] }
tempfile = "=3.27.0"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"
