[package]
name = "workflow-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "workflow-engine"
path = "src/main.rs"

[dependencies]
workflow-chat = { path = "../chat" }
workflow-environment = { path = "../environment" }
workflow-workspace = { path = "../workspace" }
workflow-filework = { path = "../filework" }
workflow-terminal = { path = "../terminal" }
schemars.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value", "arbitrary_precision"] }
base64.workspace = true
uuid.workspace = true

[dev-dependencies]
workflow-environment = { path = "../environment", features = ["test-support"] }
tempfile.workspace = true
