/* sysinv.h -- versioned syscall inventory for the engine's guest ABI.
 *
 * GENERATED by native/engine/gen/gensysinv.py from Linux v7.2.8 (linux-stable 9a66fdc0d7fd)
 * and native/engine/gen/syscalls.tsv.  Do not edit; run native/engine/gen/check.sh.
 *
 * One ABI per build: x86_64 (syscall_64.tbl, common+64 rows; x32 excluded) or aarch64
 * (generic scripts/syscall.tbl, common+64 plus arm64's syscall_abis_64).  Numbers outside
 * the table -- gaps, negatives, the x32 bit 0x40000000 -- are ENG_SC_UNKNOWN, which the
 * engine must refuse (default deny).  Lookups are O(1) over a dense static array.
 */
#ifndef ENGINE_SYSINV_H
#define ENGINE_SYSINV_H

#define ENG_SYSINV_LINUX "v7.2.8"
#define ENG_SYSINV_ABI_X86_64 1
#define ENG_SYSINV_ABI_AARCH64 2
#define ENG_SC_COUNT 11   /* number of eng_sc_class values */

typedef enum {
    ENG_SC_UNKNOWN = 0,
    ENG_SC_PASS,
    ENG_SC_PATH,
    ENG_SC_FD,
    ENG_SC_ID,
    ENG_SC_META,
    ENG_SC_EXEC,
    ENG_SC_PROC,
    ENG_SC_SOCK,
    ENG_SC_ENOSYS,
    ENG_SC_EPERM
} eng_sc_class;

const char  *eng_sysinv_name(long nr);   /* NULL if nr is not a syscall on this ABI */
eng_sc_class eng_sysinv_class(long nr);  /* ENG_SC_UNKNOWN for non-syscalls */
long         eng_sysinv_max(void);       /* highest assigned number on this ABI */
const char  *eng_sysinv_class_name(eng_sc_class c);   /* "PATH", ...; "INVALID" if out of range */
const char  *eng_sysinv_abi(void);       /* "x86_64" or "aarch64" */

#endif
