[package]
name = "workflow-filework"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
workflow-environment = { path = "../environment" }
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
