// Generates app/src/main/java/top/flysoftbeta/workflow/ui/design/theme/GeneratedColors.kt.
// Seed: the launcher icon's primary color. Scheme: SchemeTonalSpot, contrast 0 (docs/ui.md §1.3).
// Extended roles (success, warning) use the tonal palettes of fixed source colors, not harmonized,
// so that diff "+" and latency colors stay distinguishable from the teal primary.
// Run: npm ci && npm run colors   (from tools/design)
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  Hct, SchemeTonalSpot, MaterialDynamicColors as M, TonalPalette, argbFromHex, hexFromArgb,
} from '@material/material-color-utilities';

const SEED = '#286B57';
const SUCCESS_SOURCE = '#2E7D32';
const WARNING_SOURCE = '#7D5800';
const ROLES = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'background', 'onBackground', 'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'surfaceTint', 'inverseSurface', 'inverseOnSurface',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'outline', 'outlineVariant', 'scrim',
  'surfaceBright', 'surfaceDim', 'surfaceContainer', 'surfaceContainerHigh', 'surfaceContainerHighest',
  'surfaceContainerLow', 'surfaceContainerLowest',
  'primaryFixed', 'primaryFixedDim', 'onPrimaryFixed', 'onPrimaryFixedVariant',
  'secondaryFixed', 'secondaryFixedDim', 'onSecondaryFixed', 'onSecondaryFixedVariant',
  'tertiaryFixed', 'tertiaryFixedDim', 'onTertiaryFixed', 'onTertiaryFixedVariant',
];

const hex = (argb) => '0xFF' + hexFromArgb(argb).slice(1).toUpperCase();

function scheme(dark) {
  const s = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), dark, 0);
  return ROLES.map((role) => `    ${role} = Color(${hex(M[role].getArgb(s))}),`).join('\n');
}

function extended(dark) {
  const tones = dark ? { c: 80, on: 20, cont: 30, onCont: 90 } : { c: 40, on: 100, cont: 90, onCont: 10 };
  const roles = (name, source) => {
    const p = TonalPalette.fromInt(argbFromHex(source));
    const cap = name[0].toUpperCase() + name.slice(1);
    return [
      `    ${name} = Color(${hex(p.tone(tones.c))}),`,
      `    on${cap} = Color(${hex(p.tone(tones.on))}),`,
      `    ${name}Container = Color(${hex(p.tone(tones.cont))}),`,
      `    on${cap}Container = Color(${hex(p.tone(tones.onCont))}),`,
    ].join('\n');
  };
  return roles('success', SUCCESS_SOURCE) + '\n' + roles('warning', WARNING_SOURCE);
}

const out = `// GENERATED by tools/design/generate-colors.mjs — do not edit by hand.
// Seed ${SEED}, SchemeTonalSpot, contrast 0, @material/material-color-utilities 0.4.0.
package top.flysoftbeta.workflow.ui.design.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val GeneratedLightColorScheme = lightColorScheme(
${scheme(false)}
)

internal val GeneratedDarkColorScheme = darkColorScheme(
${scheme(true)}
)

internal val GeneratedLightExtendedColors = ExtendedColors(
${extended(false)}
)

internal val GeneratedDarkExtendedColors = ExtendedColors(
${extended(true)}
)
`;
const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '../../app/src/main/java/top/flysoftbeta/workflow/ui/design/theme/GeneratedColors.kt');
writeFileSync(target, out);
console.log('wrote', target);
