#!/usr/bin/env python3
"""Regenerate the Codex App-Server protocol assets used by the :agent module.

  tools/update-protocol.py                 # run the installed `codex` (or $CODEX) and regenerate everything
  tools/update-protocol.py --kotlin-only   # only regenerate CodexProtocol.kt from the checked-in inventory

Outputs (deterministic: sorted keys where order is not meaningful, schema order otherwise):
  agent/src/main/resources/protocol/codex/            JSON schema bundle + per-method files + inventory.json
  agent/src/main/kotlin/.../agent/codex/CodexProtocol.kt   method constants (generated, do not edit)
  artifacts/agent/protocol-typescript-<version>/      TypeScript bindings for humans (git-ignored)

After regenerating, run `flock artifacts/.gradle.lock ./gradlew :agent:test`: CodexCoverageTest fails
until every new method is classified in CodexCoverage.kt and the golden agent/protocol-coverage.md
is refreshed (-Pagent.updateGolden=true).
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schemas = root / "agent" / "src" / "main" / "resources" / "protocol" / "codex"
kotlin_out = root / "agent" / "src" / "main" / "kotlin" / "top" / "flysoftbeta" / "workflow" / "agent" / "codex" / "CodexProtocol.kt"
GROUPS = [("ClientRequest", "clientRequests"), ("ServerRequest", "serverRequests"),
          ("ServerNotification", "serverNotifications"), ("ClientNotification", "clientNotifications")]


def regenerate_schema(codex: str) -> None:
    version = subprocess.check_output([codex, "--version"], text=True).strip()
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "schema"
        home = Path(tmp) / "home"
        home.mkdir()
        env = dict(os.environ, CODEX_HOME=str(home))
        subprocess.run([codex, "app-server", "generate-json-schema", "--experimental", "--out", str(out)], check=True, env=env)
        ts = root / "artifacts" / "agent" / f"protocol-typescript-{version.split()[-1]}"
        subprocess.run([codex, "app-server", "generate-ts", "--experimental", "--out", str(ts)], check=True, env=env)
        if schemas.exists():
            shutil.rmtree(schemas)
        shutil.copytree(out, schemas)
    inventory = {"generated": True, "codexVersion": version, "experimentalIncluded": True,
                 "source": "https://learn.chatgpt.com/docs/app-server"}
    for name, key in GROUPS:
        schema = json.loads((schemas / (name + ".json")).read_text())
        entries = []
        for variant in schema.get("oneOf", schema.get("anyOf", [])):
            props = variant.get("properties", {})
            for method in props.get("method", {}).get("enum", []):
                entries.append({"method": method, "params": props.get("params", {}),
                                "required": variant.get("required", [])})
        inventory[key] = entries
    (schemas / "inventory.json").write_text(json.dumps(inventory, indent=2) + "\n")
    print(version)
    for key, value in inventory.items():
        if isinstance(value, list):
            print(key, len(value))


def constant_name(method: str) -> str:
    words = re.split(r"[/_\-.]", method)
    parts = []
    for word in words:
        parts.extend(re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", word).split("_"))
    return "_".join(p.upper() for p in parts if p)


def generate_kotlin() -> None:
    inventory = json.loads((schemas / "inventory.json").read_text())
    lines = [
        "// GENERATED by tools/update-protocol.py from protocol/codex/inventory.json. Do not edit.",
        f"// Source: {inventory['codexVersion']} (experimental API included: {str(inventory['experimentalIncluded']).lower()}).",
        "package top.flysoftbeta.workflow.agent.codex",
        "",
        "@Suppress(\"unused\")",
        "object CodexProtocol {",
        f"    const val VERSION = \"{inventory['codexVersion']}\"",
    ]
    for name, key in GROUPS:
        methods = [e["method"] for e in inventory[key]]
        names = [constant_name(m) for m in methods]
        dupes = {n for n in names if names.count(n) > 1}
        if dupes:
            sys.exit(f"constant name collision in {key}: {sorted(dupes)}")
        lines.append("")
        lines.append(f"    /** {len(methods)} `{key}` methods, in schema order. */")
        lines.append(f"    object {name} {{")
        for method, const in zip(methods, names):
            lines.append(f"        const val {const} = \"{method}\"")
        lines.append("")
        lines.append("        val ALL: List<String> = listOf(")
        for const in names:
            lines.append(f"            {const},")
        lines.append("        )")
        lines.append("    }")
    lines.append("}")
    kotlin_out.parent.mkdir(parents=True, exist_ok=True)
    kotlin_out.write_text("\n".join(lines) + "\n")
    print(f"wrote {kotlin_out.relative_to(root)}")


if __name__ == "__main__":
    if "--kotlin-only" not in sys.argv:
        regenerate_schema(os.environ.get("CODEX", "codex"))
    generate_kotlin()
