// GENERATED by tools/design/generate-symbols.py — do not edit by hand.
// Material Symbols Rounded (Apache-2.0), google/material-design-icons @ bd8cb85bd4bad964fe6918f79665bb40c3a8efef, opsz 20, wght 400.
package top.flysoftbeta.workflow.ui.design.icons

import androidx.annotation.DrawableRes
import top.flysoftbeta.workflow.R

/** Drawable ids of the bundled Material Symbols. `*Fill` variants are the fill-1 (active) glyphs. */
object Sym {
    /** Home / Launcher. */
    @DrawableRes val Home: Int = R.drawable.sym_home
    @DrawableRes val HomeFill: Int = R.drawable.sym_home_fill
    /** Side bar toggle (closed). */
    @DrawableRes val LeftPanelOpen: Int = R.drawable.sym_left_panel_open
    /** Side bar toggle (open). */
    @DrawableRes val LeftPanelClose: Int = R.drawable.sym_left_panel_close
    @DrawableRes val LeftPanelCloseFill: Int = R.drawable.sym_left_panel_close_fill
    /** Aux region toggle (closed). */
    @DrawableRes val RightPanelOpen: Int = R.drawable.sym_right_panel_open
    /** Aux region toggle (open). */
    @DrawableRes val RightPanelClose: Int = R.drawable.sym_right_panel_close
    @DrawableRes val RightPanelCloseFill: Int = R.drawable.sym_right_panel_close_fill
    /** Settings. */
    @DrawableRes val Settings: Int = R.drawable.sym_settings
    @DrawableRes val SettingsFill: Int = R.drawable.sym_settings_fill
    /** More menu. */
    @DrawableRes val MoreHoriz: Int = R.drawable.sym_more_horiz
    /** Expand / overflow. */
    @DrawableRes val KeyboardArrowDown: Int = R.drawable.sym_keyboard_arrow_down
    /** Collapse. */
    @DrawableRes val KeyboardArrowUp: Int = R.drawable.sym_keyboard_arrow_up
    /** Disclosure / submenu. */
    @DrawableRes val ChevronRight: Int = R.drawable.sym_chevron_right
    /** Chip dropdown. */
    @DrawableRes val ArrowDropDown: Int = R.drawable.sym_arrow_drop_down
    /** Close. */
    @DrawableRes val Close: Int = R.drawable.sym_close
    /** Add / new. */
    @DrawableRes val Add: Int = R.drawable.sym_add
    /** Confirm / selected. */
    @DrawableRes val Check: Int = R.drawable.sym_check
    /** Menu toggle on. */
    @DrawableRes val CheckBox: Int = R.drawable.sym_check_box
    /** Menu toggle off. */
    @DrawableRes val CheckBoxOutlineBlank: Int = R.drawable.sym_check_box_outline_blank
    /** Back (settings drill-in). */
    @DrawableRes val ArrowBack: Int = R.drawable.sym_arrow_back
    /** Save. */
    @DrawableRes val Save: Int = R.drawable.sym_save
    /** Undo. */
    @DrawableRes val Undo: Int = R.drawable.sym_undo
    /** Redo. */
    @DrawableRes val Redo: Int = R.drawable.sym_redo
    /** Find. */
    @DrawableRes val Search: Int = R.drawable.sym_search
    /** Attach to conversation. */
    @DrawableRes val AddComment: Int = R.drawable.sym_add_comment
    /** Word wrap. */
    @DrawableRes val WrapText: Int = R.drawable.sym_wrap_text
    /** Copy. */
    @DrawableRes val ContentCopy: Int = R.drawable.sym_content_copy
    /** Reveal in file tree. */
    @DrawableRes val AccountTree: Int = R.drawable.sym_account_tree
    /** Open with. */
    @DrawableRes val OpenInNew: Int = R.drawable.sym_open_in_new
    /** Delete / discard. */
    @DrawableRes val Delete: Int = R.drawable.sym_delete
    /** Share. */
    @DrawableRes val Share: Int = R.drawable.sym_share
    /** Fit / original size. */
    @DrawableRes val FitScreen: Int = R.drawable.sym_fit_screen
    /** Maximize / make primary. */
    @DrawableRes val OpenInFull: Int = R.drawable.sym_open_in_full
    /** Restore. */
    @DrawableRes val CloseFullscreen: Int = R.drawable.sym_close_fullscreen
    /** Split right. */
    @DrawableRes val SplitscreenRight: Int = R.drawable.sym_splitscreen_right
    /** Split down. */
    @DrawableRes val SplitscreenBottom: Int = R.drawable.sym_splitscreen_bottom
    /** Move to. */
    @DrawableRes val MoveItem: Int = R.drawable.sym_move_item
    /** Close others. */
    @DrawableRes val TabClose: Int = R.drawable.sym_tab_close
    /** New session. */
    @DrawableRes val LibraryAdd: Int = R.drawable.sym_library_add
    /** Rename. */
    @DrawableRes val Edit: Int = R.drawable.sym_edit
    /** Switch paradigm. */
    @DrawableRes val SwapHoriz: Int = R.drawable.sym_swap_horiz
    /** All sessions. */
    @DrawableRes val History: Int = R.drawable.sym_history
    /** Terminal. */
    @DrawableRes val Terminal: Int = R.drawable.sym_terminal
    @DrawableRes val TerminalFill: Int = R.drawable.sym_terminal_fill
    /** Clear. */
    @DrawableRes val ClearAll: Int = R.drawable.sym_clear_all
    /** Restart. */
    @DrawableRes val RestartAlt: Int = R.drawable.sym_restart_alt
    /** End process. */
    @DrawableRes val StopCircle: Int = R.drawable.sym_stop_circle
    @DrawableRes val StopCircleFill: Int = R.drawable.sym_stop_circle_fill
    /** Keyboard. */
    @DrawableRes val Keyboard: Int = R.drawable.sym_keyboard
    /** Latency test / speed tier. */
    @DrawableRes val Bolt: Int = R.drawable.sym_bolt
    @DrawableRes val BoltFill: Int = R.drawable.sym_bolt_fill
    /** Latency. */
    @DrawableRes val Speed: Int = R.drawable.sym_speed
    /** Edit config. */
    @DrawableRes val EditDocument: Int = R.drawable.sym_edit_document
    /** Logs. */
    @DrawableRes val ReceiptLong: Int = R.drawable.sym_receipt_long
    /** Connections. */
    @DrawableRes val Lan: Int = R.drawable.sym_lan
    /** Proxy group. */
    @DrawableRes val Language: Int = R.drawable.sym_language
    /** Start / stop. */
    @DrawableRes val PowerSettingsNew: Int = R.drawable.sym_power_settings_new
    /** Proxy (built-in app). */
    @DrawableRes val Shield: Int = R.drawable.sym_shield
    /** New file. */
    @DrawableRes val NoteAdd: Int = R.drawable.sym_note_add
    /** New folder. */
    @DrawableRes val CreateNewFolder: Int = R.drawable.sym_create_new_folder
    /** Camera. */
    @DrawableRes val PhotoCamera: Int = R.drawable.sym_photo_camera
    /** Gallery. */
    @DrawableRes val PhotoLibrary: Int = R.drawable.sym_photo_library
    /** Device files. */
    @DrawableRes val UploadFile: Int = R.drawable.sym_upload_file
    /** Filter. */
    @DrawableRes val FilterList: Int = R.drawable.sym_filter_list
    /** Collapse all. */
    @DrawableRes val UnfoldLess: Int = R.drawable.sym_unfold_less
    /** Refresh / retry. */
    @DrawableRes val Refresh: Int = R.drawable.sym_refresh
    /** Show hidden. */
    @DrawableRes val Visibility: Int = R.drawable.sym_visibility
    /** Move file. */
    @DrawableRes val DriveFileMove: Int = R.drawable.sym_drive_file_move
    /** Fork. */
    @DrawableRes val ForkRight: Int = R.drawable.sym_fork_right
    /** Copy as Markdown. */
    @DrawableRes val Markdown: Int = R.drawable.sym_markdown
    /** Archive. */
    @DrawableRes val Archive: Int = R.drawable.sym_archive
    /** Restore. */
    @DrawableRes val Unarchive: Int = R.drawable.sym_unarchive
    /** Send. */
    @DrawableRes val ArrowUpward: Int = R.drawable.sym_arrow_upward
    /** Jump to bottom. */
    @DrawableRes val ArrowDownward: Int = R.drawable.sym_arrow_downward
    /** Stop. */
    @DrawableRes val Stop: Int = R.drawable.sym_stop
    /** New conversation. */
    @DrawableRes val EditSquare: Int = R.drawable.sym_edit_square
    /** Thinking. */
    @DrawableRes val Lightbulb: Int = R.drawable.sym_lightbulb
    @DrawableRes val LightbulbFill: Int = R.drawable.sym_lightbulb_fill
    /** Attachment. */
    @DrawableRes val AttachFile: Int = R.drawable.sym_attach_file
    /** Plan. */
    @DrawableRes val Checklist: Int = R.drawable.sym_checklist
    /** Codex backend badge. */
    @DrawableRes val Hexagon: Int = R.drawable.sym_hexagon
    /** Claude Code backend badge. */
    @DrawableRes val Asterisk: Int = R.drawable.sym_asterisk
    /** API key login. */
    @DrawableRes val Key: Int = R.drawable.sym_key
    /** Warning / full access. */
    @DrawableRes val Warning: Int = R.drawable.sym_warning
    @DrawableRes val WarningFill: Int = R.drawable.sym_warning_fill
    /** Error. */
    @DrawableRes val Error: Int = R.drawable.sym_error
    @DrawableRes val ErrorFill: Int = R.drawable.sym_error_fill
    /** Details. */
    @DrawableRes val Info: Int = R.drawable.sym_info
    @DrawableRes val InfoFill: Int = R.drawable.sym_info_fill
    /** Invalid drop target. */
    @DrawableRes val Block: Int = R.drawable.sym_block
    /** Success. */
    @DrawableRes val CheckCircle: Int = R.drawable.sym_check_circle
    @DrawableRes val CheckCircleFill: Int = R.drawable.sym_check_circle_fill
    /** Remove / failed. */
    @DrawableRes val Cancel: Int = R.drawable.sym_cancel
    /** Lock screen. */
    @DrawableRes val Lock: Int = R.drawable.sym_lock
    @DrawableRes val LockFill: Int = R.drawable.sym_lock_fill
    /** Grayscale. */
    @DrawableRes val Contrast: Int = R.drawable.sym_contrast
    @DrawableRes val ContrastFill: Int = R.drawable.sym_contrast_fill
    /** Brightness. */
    @DrawableRes val LightMode: Int = R.drawable.sym_light_mode
    @DrawableRes val LightModeFill: Int = R.drawable.sym_light_mode_fill
    /** Apps. */
    @DrawableRes val Apps: Int = R.drawable.sym_apps
    /** Drag handle. */
    @DrawableRes val DragIndicator: Int = R.drawable.sym_drag_indicator
    /** Time. */
    @DrawableRes val Schedule: Int = R.drawable.sym_schedule
    /** Link. */
    @DrawableRes val Link: Int = R.drawable.sym_link
    /** Workbench (built-in app). */
    @DrawableRes val SpaceDashboard: Int = R.drawable.sym_space_dashboard
    /** Conversation panel. */
    @DrawableRes val Chat: Int = R.drawable.sym_chat
    /** Remove from Apps. */
    @DrawableRes val DoNotDisturbOn: Int = R.drawable.sym_do_not_disturb_on
    /** Generic file. */
    @DrawableRes val Draft: Int = R.drawable.sym_draft
    @DrawableRes val DraftFill: Int = R.drawable.sym_draft_fill
    /** Text file. */
    @DrawableRes val Description: Int = R.drawable.sym_description
    @DrawableRes val DescriptionFill: Int = R.drawable.sym_description_fill
    /** Markdown. */
    @DrawableRes val Article: Int = R.drawable.sym_article
    @DrawableRes val ArticleFill: Int = R.drawable.sym_article_fill
    /** Source code. */
    @DrawableRes val Code: Int = R.drawable.sym_code
    /** JavaScript / TypeScript. */
    @DrawableRes val Javascript: Int = R.drawable.sym_javascript
    /** HTML / XML. */
    @DrawableRes val Html: Int = R.drawable.sym_html
    /** CSS. */
    @DrawableRes val Css: Int = R.drawable.sym_css
    /** JSON / YAML / TOML. */
    @DrawableRes val DataObject: Int = R.drawable.sym_data_object
    /** Image. */
    @DrawableRes val Image: Int = R.drawable.sym_image
    @DrawableRes val ImageFill: Int = R.drawable.sym_image_fill
    /** PDF. */
    @DrawableRes val PictureAsPdf: Int = R.drawable.sym_picture_as_pdf
    /** Archive file. */
    @DrawableRes val FolderZip: Int = R.drawable.sym_folder_zip
    /** CSV / TSV. */
    @DrawableRes val Table: Int = R.drawable.sym_table
    /** Audio. */
    @DrawableRes val AudioFile: Int = R.drawable.sym_audio_file
    /** Video. */
    @DrawableRes val VideoFile: Int = R.drawable.sym_video_file
    /** Folder. */
    @DrawableRes val Folder: Int = R.drawable.sym_folder
    @DrawableRes val FolderFill: Int = R.drawable.sym_folder_fill
    /** Open folder. */
    @DrawableRes val FolderOpen: Int = R.drawable.sym_folder_open
    @DrawableRes val FolderOpenFill: Int = R.drawable.sym_folder_open_fill

    /** Every bundled glyph by Material Symbols name (design gallery, tests). */
    val all: List<Pair<String, Int>> by lazy {
        listOf(
            "home" to Home,
            "home (fill)" to HomeFill,
            "left_panel_open" to LeftPanelOpen,
            "left_panel_close" to LeftPanelClose,
            "left_panel_close (fill)" to LeftPanelCloseFill,
            "right_panel_open" to RightPanelOpen,
            "right_panel_close" to RightPanelClose,
            "right_panel_close (fill)" to RightPanelCloseFill,
            "settings" to Settings,
            "settings (fill)" to SettingsFill,
            "more_horiz" to MoreHoriz,
            "keyboard_arrow_down" to KeyboardArrowDown,
            "keyboard_arrow_up" to KeyboardArrowUp,
            "chevron_right" to ChevronRight,
            "arrow_drop_down" to ArrowDropDown,
            "close" to Close,
            "add" to Add,
            "check" to Check,
            "check_box" to CheckBox,
            "check_box_outline_blank" to CheckBoxOutlineBlank,
            "arrow_back" to ArrowBack,
            "save" to Save,
            "undo" to Undo,
            "redo" to Redo,
            "search" to Search,
            "add_comment" to AddComment,
            "wrap_text" to WrapText,
            "content_copy" to ContentCopy,
            "account_tree" to AccountTree,
            "open_in_new" to OpenInNew,
            "delete" to Delete,
            "share" to Share,
            "fit_screen" to FitScreen,
            "open_in_full" to OpenInFull,
            "close_fullscreen" to CloseFullscreen,
            "splitscreen_right" to SplitscreenRight,
            "splitscreen_bottom" to SplitscreenBottom,
            "move_item" to MoveItem,
            "tab_close" to TabClose,
            "library_add" to LibraryAdd,
            "edit" to Edit,
            "swap_horiz" to SwapHoriz,
            "history" to History,
            "terminal" to Terminal,
            "terminal (fill)" to TerminalFill,
            "clear_all" to ClearAll,
            "restart_alt" to RestartAlt,
            "stop_circle" to StopCircle,
            "stop_circle (fill)" to StopCircleFill,
            "keyboard" to Keyboard,
            "bolt" to Bolt,
            "bolt (fill)" to BoltFill,
            "speed" to Speed,
            "edit_document" to EditDocument,
            "receipt_long" to ReceiptLong,
            "lan" to Lan,
            "language" to Language,
            "power_settings_new" to PowerSettingsNew,
            "shield" to Shield,
            "note_add" to NoteAdd,
            "create_new_folder" to CreateNewFolder,
            "photo_camera" to PhotoCamera,
            "photo_library" to PhotoLibrary,
            "upload_file" to UploadFile,
            "filter_list" to FilterList,
            "unfold_less" to UnfoldLess,
            "refresh" to Refresh,
            "visibility" to Visibility,
            "drive_file_move" to DriveFileMove,
            "fork_right" to ForkRight,
            "markdown" to Markdown,
            "archive" to Archive,
            "unarchive" to Unarchive,
            "arrow_upward" to ArrowUpward,
            "arrow_downward" to ArrowDownward,
            "stop" to Stop,
            "edit_square" to EditSquare,
            "lightbulb" to Lightbulb,
            "lightbulb (fill)" to LightbulbFill,
            "attach_file" to AttachFile,
            "checklist" to Checklist,
            "hexagon" to Hexagon,
            "asterisk" to Asterisk,
            "key" to Key,
            "warning" to Warning,
            "warning (fill)" to WarningFill,
            "error" to Error,
            "error (fill)" to ErrorFill,
            "info" to Info,
            "info (fill)" to InfoFill,
            "block" to Block,
            "check_circle" to CheckCircle,
            "check_circle (fill)" to CheckCircleFill,
            "cancel" to Cancel,
            "lock" to Lock,
            "lock (fill)" to LockFill,
            "contrast" to Contrast,
            "contrast (fill)" to ContrastFill,
            "light_mode" to LightMode,
            "light_mode (fill)" to LightModeFill,
            "apps" to Apps,
            "drag_indicator" to DragIndicator,
            "schedule" to Schedule,
            "link" to Link,
            "space_dashboard" to SpaceDashboard,
            "chat" to Chat,
            "do_not_disturb_on" to DoNotDisturbOn,
            "draft" to Draft,
            "draft (fill)" to DraftFill,
            "description" to Description,
            "description (fill)" to DescriptionFill,
            "article" to Article,
            "article (fill)" to ArticleFill,
            "code" to Code,
            "javascript" to Javascript,
            "html" to Html,
            "css" to Css,
            "data_object" to DataObject,
            "image" to Image,
            "image (fill)" to ImageFill,
            "picture_as_pdf" to PictureAsPdf,
            "folder_zip" to FolderZip,
            "table" to Table,
            "audio_file" to AudioFile,
            "video_file" to VideoFile,
            "folder" to Folder,
            "folder (fill)" to FolderFill,
            "folder_open" to FolderOpen,
            "folder_open (fill)" to FolderOpenFill,
        )
    }
}
